In [2]:
import os
os.getcwd()

'C:\\Users\\point\\anaconda_projects\\95c83e6f-79ff-4276-a53f-317122c30125'

In [3]:
import pandas as pd
file=pd.read_csv("ecommerce_customer_churn_dataset.csv")

In [19]:
import numpy as np

In [22]:
file.head()

,age,gender,country,city,membership_years,login_frequency,session_duration_avg,pages_per_session,cart_abandonment_rate,wishlist_items,...,customer_service_calls,product_reviews_written,social_media_engagement_score,mobile_app_usage,payment_method_diversity,lifetime_value,credit_balance,churned,signup_quarter,activity_status
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,9.0,4.0,16.3,20.8,1.0,953.33,2278.0,0,Q1,Active
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,7.0,3.0,0.0,23.3,3.0,1067.47,3028.0,0,Q4,Active
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,4.0,1.0,0.0,8.8,1.0,1289.75,2317.0,0,Q4,Active
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,2.0,5.0,85.9,31.0,3.0,2340.92,2674.0,0,Q1,Active
4,35.0,Male,India,Delhi,3.1,29.0,51.4,0.0,19.1,9.0,...,1.0,11.0,83.0,50.4,4.0,3041.29,5354.0,0,Q4,Active

In [4]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            47505 non-null  float64
 1   Gender                         50000 non-null  object
 2   Country                        50000 non-null  object
 3   City                           50000 non-null  object
 4   Membership_Years               50000 non-null  float64
 5   Login_Frequency                50000 non-null  float64
 6   Session_Duration_Avg           46601 non-null  float64
 7   Pages_Per_Session              47000 non-null  float64
 8   Cart_Abandonment_Rate          50000 non-null  float64
 9   Wishlist_Items                 46000 non-null  float64
 10  Total_Purchases                50000 non-null  float64
 11  Average_Order_Value            50000 non-null  float64
 12  Days_Since_Last_Purchase       47000 non-null  float64
 13  Discount_Usage_Rate            46500 non-null  float64
 14  Returns_Rate                   45509 non-null  float64
 15  Email_Open_Rate                47472 non-null  float64
 16  Customer_Service_Calls         49832 non-null  float64
 17  Product_Reviews_Written        46500 non-null  float64
 18  Social_Media_Engagement_Score  44000 non-null  float64
 19  Mobile_App_Usage               45000 non-null  float64
 20  Payment_Method_Diversity       47500 non-null  float64
 21  Lifetime_Value                 50000 non-null  float64
 22  Credit_Balance                 44500 non-null  float64
 23  Churned                        50000 non-null  int64
 24  Signup_Quarter                 50000 non-null  object
dtypes: float64(20), int64(1), object(4)
memory usage: 9.5+ MB

In [21]:
file.describe(include='all')

,age,gender,country,city,membership_years,login_frequency,session_duration_avg,pages_per_session,cart_abandonment_rate,wishlist_items,...,customer_service_calls,product_reviews_written,social_media_engagement_score,mobile_app_usage,payment_method_diversity,lifetime_value,credit_balance,churned,signup_quarter,activity_status
count,50000.000000,50000,50000,50000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,...,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000,50000
unique,NaN,3,8,40,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,2
top,NaN,Female,USA,Houston,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q3,Active
freq,NaN,25116,17384,3549,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12558,45970
mean,37.812800,NaN,NaN,NaN,2.984009,11.624660,25.780376,8.213542,57.079973,3.954520,...,5.66274,2.653580,25.840730,17.434446,2.286180,1440.626292,1749.947600,0.289000,NaN,NaN
std,11.535688,NaN,NaN,NaN,2.059105,7.810657,12.594554,4.210062,16.282723,3.274206,...,2.69171,2.361001,21.530263,10.659451,1.121421,907.249443,1309.277071,0.453302,NaN,NaN
min,5.000000,NaN,NaN,NaN,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,NaN,NaN
25%,30.000000,NaN,NaN,NaN,1.400000,6.000000,18.000000,5.500000,46.400000,1.000000,...,4.00000,1.000000,5.700000,10.200000,1.000000,789.817500,647.000000,0.000000,NaN,NaN
50%,38.000000,NaN,NaN,NaN,2.500000,11.000000,25.700000,8.100000,58.100000,3.000000,...,5.00000,2.000000,23.700000,17.200000,2.000000,1243.415000,1697.000000,0.000000,NaN,NaN
75%,45.000000,NaN,NaN,NaN,4.000000,17.000000,34.000000,11.000000,68.700000,6.000000,...,7.00000,4.000000,40.700000,24.600000,3.000000,1874.000000,2664.000000,1.000000,NaN,NaN
max,200.000000,NaN,NaN,NaN,10.000000,46.000000,75.600000,24.100000,143.743350,28.000000,...,21.00000,21.000000,100.000000,61.900000,5.000000,8987.240000,7197.000000,1.000000,NaN,NaN

In [8]:
file.columns=file.columns.str.lower()

In [5]:
file.isnull().sum()

Age                              2495
Gender                              0
Country                             0
City                                0
Membership_Years                    0
Login_Frequency                     0
Session_Duration_Avg             3399
Pages_Per_Session                3000
Cart_Abandonment_Rate               0
Wishlist_Items                   4000
Total_Purchases                     0
Average_Order_Value                 0
Days_Since_Last_Purchase         3000
Discount_Usage_Rate              3500
Returns_Rate                     4491
Email_Open_Rate                  2528
Customer_Service_Calls            168
Product_Reviews_Written          3500
Social_Media_Engagement_Score    6000
Mobile_App_Usage                 5000
Payment_Method_Diversity         2500
Lifetime_Value                      0
Credit_Balance                   5500
Churned                             0
Signup_Quarter                      0
dtype: int64

In [6]:
#Replacing Null Values of Age Column To Median
file['age']=file['age'].fillna(file['age'].median())

KeyError: 'age'

In [13]:
cols=['session_duration_avg','pages_per_session','wishlist_items','returns_rate','product_reviews_written','email_open_rate',
      'discount_usage_rate','social_media_engagement_score','mobile_app_usage','credit_balance','customer_service_calls']
file[cols]=file[cols].fillna(0)

In [15]:
file['payment_method_diversity']=file['payment_method_diversity'].fillna(1)

In [16]:
max_days=file['days_since_last_purchase'].max()
file['days_since_last_purchase']=file['days_since_last_purchase'].fillna(max_days+1)

In [20]:
file['activity_status']=np.where(file['login_frequency']==0,'Inactive','Active')

In [24]:
file['purchase_type']=pd.cut(file['total_purchases'],bins=[-1,1,5,10,file['total_purchases'].max()],labels=['One-Time','Low','Medium','High'])

In [25]:
file['value_segment']=pd.qcut(file['lifetime_value'],q=3,labels=['Low Value','Medium Value','High Value'])

In [26]:
file['recency_bucket']=pd.cut(file['days_since_last_purchase'],bins=[-1,30,90,180,file['days_since_last_purchase'].max()],labels=['30 Days','30-90 Days',
                                                                                                                                  '90-180 Days','180+ Days'])

In [29]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\point\anaconda3\lib\site-packages (9.5.0)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import mysql.connector

In [31]:
from sqlalchemy import create_engine
username="root"
password="root"
host="localhost"
port=3306
database="ecommerce_data"
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name='ecommerce_customer_data'
file.to_sql(table_name,engine,if_exists='replace',index=False)
print(f"Data Succesfully loaded into table {table_name} in {database} database")

Data Succesfully loaded into table ecommerce_customer_data in ecommerce_data database